"""Update Pickup model fields

Revision ID: 49cb47e91afc
Revises: 509a20ec0567
Create Date: 2025-07-11 12:12:13.056920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49cb47e91afc'
down_revision = '509a20ec0567'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pickups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pin_code', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('waste_type', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('pickup_date', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('time_slot', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pickups', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('status')
        batch_op.drop_column('time_slot')
        batch_op.drop_column('pickup_date')
        batch_op.drop_column('waste_type')
        batch_op.drop_column('pin_code')

    # ### end Alembic commands ###
