"""Add Pickup and Complaint models

Revision ID: 509a20ec0567
Revises: 834a97c6fda4
Create Date: 2025-07-11 11:58:12.204570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '509a20ec0567'
down_revision = '834a97c6fda4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('complaints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pickups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pickups')
    op.drop_table('complaints')
    # ### end Alembic commands ###
