"""Update Complaint model fields

Revision ID: 939cd63d99f0
Revises: 49cb47e91afc
Create Date: 2025-07-11 12:29:56.187139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '939cd63d99f0'
down_revision = '49cb47e91afc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaints', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('photo_path', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('location', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaints', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('status')
        batch_op.drop_column('location')
        batch_op.drop_column('photo_path')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
